name: Deploy to production --> www.futbolyamigos.com.ar

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      NEXT_PUBLIC_API_URL_BASE: ${{ secrets.NEXT_PUBLIC_API_URL_BASE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build UI
        run: npx nx run ui:export
      - name: Build API
        run: npx nx run api:build:production
      - name: Deploy UI
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
      - name: Create package Api
        uses: actions/upload-artifact@v3
        with:
          name: package-api
          path: dist\apps\api\main.js
          if-no-files-found: error
